### ISSUE TITLE
Wrong path for the encryption cert in the AuthnRequest

### ISSUE THREAD

**Issue by rhoerbe** [its-dirg/pefim-proxy#4]
If the proxy receives the cert in the correct location it does not forward the extension element.

The path needs to be corrected to include ds:KeyInfo in the path:ns3:Extensions

```
    <ns4:SPCertEnc>
      <ds:KeyInfo>
        <ns2:X509Data>
          <ns2:X509Certificate>
```

There should be a configuration item that (by default) forces the proxy the reject an AuthnRequest if the encryption certificate is missing. To convey the message, an top-level <StatusCode>  of urn:oasis:names:tc:SAML:2.0:status:Requester shall be returned, with <StatusMessage> set to "Element /samlp:AuthnRequest/samlp:extension/pefim:SPCertEnc/ds:KeyInfo/ ds:X509Data/ds:X509Certificate" missing.

**Comment by HaToHo** [comment]
Add the complete authnrequest that is supposed to work so I can create a unit test case.

**Comment by rhoerbe** [comment]
This is the 'offending' AuthnRequest:

``` xml
<ns0:AuthnRequest
    xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol"
    xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion"
    xmlns:ns2="urn:net:eustix:names:tc:PEFIM:0.0:assertion"
    xmlns:ns3="http://www.w3.org/2000/09/xmldsig#"
    AssertionConsumerServiceURL="https://pefim-sp.cryonslab.org/Shibboleth.sso/SAML2/POST"
    Destination="https://pefim-sb.cryonslab.org:8999/sso/redirect"
    ID="_ea6915c0fb454cce8e7618c7120e6946"
    IssueInstant="2015-04-30T07:44:48Z"
    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    Version="2.0">

    <ns1:Issuer>https://pefim-sp.cryonslab.org/shibboleth</ns1:Issuer>
    <ns0:Extensions>
        <ns2:SPCertEnc>
            <ns3:KeyInfo>
                <ns3:X509Data>
                    <ns3:X509Certificate>MIID3DCCAsSgAwIBAgIJAI4Pki06znISMA0GCSqGSIb3DQEBCwUAMIGBMQswCQYD
VQQGEwJBVDEPMA0GA1UECAwGVmllbm5hMQ8wDQYDVQQHDAZWaWVubmExITAfBgNV
BAoMGENyeXB0YXMgaXQtU2VjdXJpdHkgR21iSDEPMA0GA1UECwwGQ3J5b25zMRww
GgYDVQQDDBNQZUZJTSBTaG9ydCBUZXJtIENBMB4XDTE1MDQyOTE1MjQwMloXDTE2
MDQyODE1MjQwMlowTzELMAkGA1UEBhMCQVQxDzANBgNVBAcMBlZpZW5uYTEhMB8G
A1UECgwYQ3J5cHRhcyBpdC1TZWN1cml0eSBHbWJIMQwwCgYDVQQDDAM0NjcwggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDdWtGDA4CP1gMWxt98HzyT0z/h
dne9cTelZ4PNDnPt+lhPYrEG10WF1zgZXmr1oRbOMgtwJASlDbc5TQVUzOdlDKf2
aTWStKAN3Y8Ly7tmHfA0GKQXqE5tS4HaE583HKsgs+Lz6SCnNz//E5f1O93IY49q
cQZgy8ERPIYXaluXTkMOWZDNUmKjP/RU5OSeTIzoEuOA5MPE8m5B6h7Fuk+TW7DM
auF/RAu0/ANDq/zW6H/PwRw7rRBtsZ5LGAvKapdON59QqMfcuwPZYGhJNnHWtBDR
9FPuun/yVEF8MSdJHPcSHuUZyxuXcARhk3idQyEwfgmgbIITBTixL/io2H1lAgMB
AAGjgYcwgYQwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYdT3BlblNTTCBHZW5l
cmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFIkNOCnfihtkqg74+NjysAhUlLzl
MB8GA1UdIwQYMBaAFCxkXBiOg0RDk+egva0/Ww6s8+SxMAkGA1UdEQQCMAAwDQYJ
KoZIhvcNAQELBQADggEBALP0zeH0gjKTeI1XMku/BaEyPOsfV1bpBNjD30uSybVu
DRVWvyoGs4DlPCgiHtZUjODIogyHwrhLGhMWYneuKfgnnQ39Ve7BRbgxdx161MtQ
ZYtpnxkdyKL6/WRZtRV8D6vWv3VKMWbwJAOTT4gRHrHPEH1fQZvG9Wpli8802OKE
9EzA73CHefFn863zOGTAxVOMFXQ1kTGLajVq4KPYxni7jEyJwvGNP6dNX5MmX4lt
MxeyuJy8PN2ieNy9vFqdtvTZEXl9fq3fm2fOMGVNXQYn73BXRD5I1HKt37QW9AIO
yVSB8xx11Js3Xmm3Nx/iSce5sdO/oVet6+XAFvpiF9w=
                    </ns3:X509Certificate>
                </ns3:X509Data>
            </ns3:KeyInfo>
        </ns2:SPCertEnc>
    </ns0:Extensions>
    <ns0:NameIDPolicy AllowCreate="1" />
</ns0:AuthnRequest>
```

**Comment by HaToHo** [comment]
I have a fix in the develop bransch for pefim_proxy and my pysaml2 git repo. I have only tested with unit testcases. 

A question:

Is it ok to use RequestUnsupported instead of Requester? pysaml2 have full support for ReqestUnsupported so its easier to add support for that response. You can see the XML response generated by the proxy.

<?xml version="1.0" encoding="UTF-8"?>
<ns0:Response xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" Destination="http://test.sp.se:8900/acs/post" ID="id-2iWnLvqLXEc1nghFu" InResponseTo="id-HKsq7dz1qoFyNkWKR" IssueInstant="2015-05-04T14:49:37Z" Version="2.0"><ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://localhost:8999proxy.xml/ns1:Issuer<ns2:Signature Id="Signature1">ns2:SignedInfo<ns2:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ns2:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><ns2:Reference URI="#id-2iWnLvqLXEc1nghFu">ns2:Transforms<ns2:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ns2:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>/ns2:Transforms<ns2:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>ns2:DigestValueJ3MTCnLmzomoXoL9YNcc3q4UFik=/ns2:DigestValue/ns2:Reference/ns2:SignedInfons2:SignatureValueMdfTtdi62aFWEoaUIt3vB8isCixggMHdsWpz7RJ3UETfbj50Ci7WQe8jws7o3Dt+
inXfChTG4d+W/pKvWFJoF2P9J8K+FojoEpWh/L+65EDIEk6TsRtGgT/E0CQ4oX3X
Zq/208KF5nIKidrCgVrna2LYmdHrS4cQjVnRX2lemnc=/ns2:SignatureValuens2:KeyInfons2:X509Datans2:X509CertificateMIICIzCCAYwCAXcwDQYJKoZIhvcNAQELBQAwWjELMAkGA1UEBhMCc2UxCzAJBgNVBAgTAmFjMQ0wCwYDVQQHEwRVbWVhMQwwCgYDVQQKEwNJVFMxDTALBgNVBAsTBERJUkcxEjAQBgNVBAMTCWxvY2FsaG9zdDAeFw0xNDAzMTkxNzE5MzlaFw0yNDAzMTYxNzE5MzlaMFoxCzAJBgNVBAYTAnNlMQswCQYDVQQIEwJhYzENMAsGA1UEBxMEVW1lYTEMMAoGA1UEChMDSVRTMQ0wCwYDVQQLEwRESVJHMRIwEAYDVQQDEwlsb2NhbGhvc3QwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBALswQbMz6dKL4FEKu+O3GYDfaniyxcfizsHaiehuh5jufrlGZw/zMMttteTRhpjtTFN2/R68d1kh8pmO+HV7u+53h+C33I178ZsOquSovGe1AWmzDzp2j6CRdQYdZaMCc4YxtwEXs7570YmnPLKhz8aHdiQRHhtx1cqdPPStkz67AgMBAAEwDQYJKoZIhvcNAQELBQADgYEApQ5znEdhsJBs+ew81X9pkUKZ/ruu/p2OPfYmKzdFnK6mq9bF5CEIaIkvbSJjpECicmGCNw9ATJXylnwFLnfxw6d+YGi4XPuo64NSG00ycnMSTMJ8OR5ForcF89v72BLRDYo6yXeNDw722ul0lPzH54CNQzsm4N/5w5iStnOT1TQ=/ns2:X509Certificate/ns2:X509Data/ns2:KeyInfo/ns2:Signaturens0:Status<ns0:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder"><ns0:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:RequestUnsupported"/>/ns0:StatusCodens0:StatusMessageElement /samlp:AuthnRequest/samlp:extension/pefim:SPCertEnc/ds:KeyInfo/ ds:X509Data/ds:X509Certificate missing/ns0:StatusMessage/ns0:Status/ns0:Response

**Comment by rhoerbe** [comment]
Yes, this is also better in terms of SAML semantics, because it is issues for a generally correct SAML request that does not match additional requirements.

**Comment by HaToHo** [comment]
Fixed, please verify and comment if more changes is needed or close.
